### ISSUE TITLE
Rails 6.1 undefined method 'day' for 1:Integer

### ISSUE THREAD

**Issue by DonaldoSoWell** [Gokul595/api_guard#51] opened 2021-07-09 21:57 UTC
**Describe the bug**
`undefined method 'day' for 1:Integer `error is raised while running one of the following commands :
- rails t
- rails c
- rails s

**Gem version (please complete the following information):**
 - Ruby: 2.7.3
 - Rails 6.1.4
 - API Guard 0.5.1

**Comment by Gokul595** [comment] 2021-08-06 15:23
@DonaldoSoWell Sorry for checking this late. I couldn't reproduce this bug, tried with the ruby and rails version mentioned by you. Do you mind sharing the complete log that you see when you get this error?

**Comment by Gokul595** [comment] 2022-07-22 15:23
Closing this for now. Feel free to reopen.

**Closed** 2022-07-22 15:22 UTC
Labels: bug
